version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile-env
    container_name: backend_dev
    volumes:
      - ./backend:/backend
    ports:
      - "3001:3000"
    environment:
      - RAILS_ENV=development
    command: >
      bash -c "bundle check || bundle install && 
              rails server -b '0.0.0.0'"
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile-env
    container_name: frontend_dev
    volumes:
      - ./frontend:/frontend
    ports:
      - "3002:3000"
    command: >
      bash -c "npm install &&
               npm start"  